# Generated by Django 4.0.4 on 2022-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_text_url_origin_url_url_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short',
        ),
        migrations.AddField(
            model_name='url',
            name='hash_salted_url',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='url',
            name='salt',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
