# Generated by Django 4.0.4 on 2022-06-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_url_short_url_hash_salted_url_url_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash_salted_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='url',
            name='salt',
            field=models.CharField(max_length=6),
        ),
    ]
